import Head from "next/head";
import { ReactNode } from "react";

type Props = {
    title?: string;
    children: ReactNode;
};

export default function Layout({ title, children }: Props) {
    return (
        <div>
            <Head>
                <title>{title || "Cogniforge"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </div>
    );
}
